language: java
install: true

sudo: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
  
stages:
  - name: build
  - name: snapshotBranch
    if: tag IS blank AND branch =~ /^(\d+.)+\d+-SNAPSHOT$/
  - name: releaseTag
    if: tag IS present
    
jobs:
  include:
    - stage: build
      script: /bin/sh ./gradlew build
    - stage: snapshotBranch
      script: /bin/sh ./gradlew publish artifactoryPublish -x test -Dsnapshot=true -Dbintray.user=$BINTRAY_USER -Dbintray.key=$BINTRAY_KEY -Dbuild.number=$TRAVIS_BUILD_NUMBER
    - stage: releaseTag
      script: /bin/sh ./gradlew publish bintrayUpload -x test -Dbintray.user=$BINTRAY_USER -Dbintray.key=$BINTRAY_KEY -Dbuild.number=$TRAVIS_BUILD_NUMBER
      
